### ISSUE TITLE
계정을 등록할 수 없어요

### ISSUE THREAD

**Issue by MagicalLas** [sunrabbit123/GRIG#13]
안녕하세요, 계정을 등록하기위해 `student170420@gsm.hs.kr` 로 메일 인증을 하려고했지만, 잘 작동하지 않는 것 같습니다.
확인 부탁드립니다.

**Comment by sunrabbit123** [comment]
의견 감사합니다.
작동하지 않는 이유로 한가지가 떠오릅니다.

1. 현재 GSM 학생 계정의 형태를 `s\d{5}@gsm.hs.kr`로 알고 있습니다.  
    이로 인하여 로직상의 에러가 생길 수 있을 것 같습니다.

하지만 이외에도 다른 상황이 발생할 수 있기때문에
더 자세한 정보들을 첨부해주시면 감사할 것 같습니다.

관심을 가져주셔서 감사합니다 :D

**Comment by sunrabbit123** [comment]
버그가 발생하였지만, 최우선적으로 등록되도록 조치하였습니다.

버그의 원인은 이메일로 발송된 링크에 첨부되어 있는 토큰이 유효하지않다는 점이였습니다.
아마도 최초의 시도에 이메일의 형태가 달라 기수를 구하다가 에러가 난 것으로 보입니다.

1기의 이메일 형태를 알지못해 생긴 버그였습니다.

**Comment by sunrabbit123** [comment]
오늘 내로 수정 될 것으로 예상되며, 자세한 사항은 아래의 링크로 부탁드립니다.

> https://github.com/GRI-G

감사합니다.
