### ISSUE TITLE
인증페이지 버튼 오류

### ISSUE THREAD

**Issue by yoosion030** [sunrabbit123/GRIG#6]
![image](https://user-images.githubusercontent.com/80191860/135409110-ed0a899f-ff52-4890-bf0b-8d2f5798a22c.png)
완료버튼을 눌러도 넘어가 지지 않습니다.

**Comment by sunrabbit123** [comment]
왜 안넘어갈까 하핳...
이슈 감사합니다

**Comment by sunrabbit123** [comment]
해당 파트는 https://github.com/sunrabbit123/GRIG-OpenAPI 의 문제입니다.

fix : sunrabbit123/GRIG#6

@sunrabbit123
sunrabbit123 committed 1 minute ago

에서 해결한 줄 알았으나 아직 안되서 다시 엽니다 인생...
